# Generated by Django 3.2.8 on 2021-10-15 09:31

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_human', models.CharField(max_length=64, verbose_name='Class name for human')),
                ('name', models.CharField(max_length=64, verbose_name='Class name')),
                ('hint', models.JSONField(default=core.models.default_class_hint, verbose_name='Class hint')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_human', models.CharField(max_length=64, verbose_name='Attr name for human')),
                ('name', models.CharField(max_length=64, verbose_name='Attr name')),
                ('hint', models.JSONField(default=core.models.default_attr_hint, verbose_name='Attr hint')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
            ],
        ),
    ]
